raw_data_processor_config:
  db_name: proteingym
  raw_data_path:
    proteingym_dir: data/input/proteingym/DMS_ProteinGym_substitutions/
options:
  possible_db_processing:
    - 5fold
    - all_test
    - all_generated
  db:
    - A4_HUMAN_Seuma_2022.csv
    - ACE2_HUMAN_Chan_2020.csv
    - ADRB2_HUMAN_Jones_2020.csv
    - AICDA_HUMAN_Gajula_2014_3cycles.csv
    - AMFR_HUMAN_Tsuboyama_2023_4G3O.csv
    - B2L11_HUMAN_Dutta_2010_binding-Mcl-1.csv
    - BRCA1_HUMAN_Findlay_2018.csv
    - BRCA2_HUMAN_Erwood_2022_HEK293T.csv
    - CALM1_HUMAN_Weile_2017.csv
    - CAR11_HUMAN_Meitlis_2020_gof.csv
    - CAR11_HUMAN_Meitlis_2020_lof.csv
    - CASP3_HUMAN_Roychowdhury_2020.csv
    - CASP7_HUMAN_Roychowdhury_2020.csv
    - CBPA2_HUMAN_Tsuboyama_2023_1O6X.csv
    - CBS_HUMAN_Sun_2020.csv
    - CBX4_HUMAN_Tsuboyama_2023_2K28.csv
    - CCR5_HUMAN_Gill_2023.csv
    - CD19_HUMAN_Klesmith_2019_FMC_singles.csv
    - CP2C9_HUMAN_Amorosi_2021_abundance.csv
    - CP2C9_HUMAN_Amorosi_2021_activity.csv
    - DLG4_HUMAN_Faure_2021.csv
    - DNJA1_HUMAN_Tsuboyama_2023_2LO1.csv
    - EPHB2_HUMAN_Tsuboyama_2023_1F0M.csv
    - ERBB2_HUMAN_Elazar_2016.csv
    - FKBP3_HUMAN_Tsuboyama_2023_2KFV.csv
    - GDIA_HUMAN_Silverstein_2021.csv
    - GLPA_HUMAN_Elazar_2016.csv
    - GRB2_HUMAN_Faure_2021.csv
    - HECD1_HUMAN_Tsuboyama_2023_3DKM.csv
    - HEM3_HUMAN_Loggerenberg_2023.csv
    - HMDH_HUMAN_Jiang_2019.csv
    - HXK4_HUMAN_Gersing_2022_activity.csv
    - HXK4_HUMAN_Gersing_2023_abundance.csv
    - ILF3_HUMAN_Tsuboyama_2023_2L33.csv
    - KCNE1_HUMAN_Muhammad_2023_expression.csv
    - KCNE1_HUMAN_Muhammad_2023_function.csv
    - KCNH2_HUMAN_Kozek_2020.csv
    - LYAM1_HUMAN_Elazar_2016.csv
    - MET_HUMAN_Estevam_2023.csv
    - MK01_HUMAN_Brenan_2016.csv
    - MSH2_HUMAN_Jia_2020.csv
    - MTHR_HUMAN_Weile_2021.csv
    - NKX31_HUMAN_Tsuboyama_2023_2L9R.csv
    - NPC1_HUMAN_Erwood_2022_HEK293T.csv
    - NPC1_HUMAN_Erwood_2022_RPE1.csv
    - NUD15_HUMAN_Suiter_2020.csv
    - OBSCN_HUMAN_Tsuboyama_2023_1V1C.csv
    - OPSD_HUMAN_Wan_2019.csv
    - OTC_HUMAN_Lo_2023.csv
    - OTU7A_HUMAN_Tsuboyama_2023_2L2D.csv
    - P53_HUMAN_Giacomelli_2018_Null_Etoposide.csv
    - P53_HUMAN_Giacomelli_2018_Null_Nutlin.csv
    - P53_HUMAN_Giacomelli_2018_WT_Nutlin.csv
    - P53_HUMAN_Kotler_2018.csv
    - PAI1_HUMAN_Huttinger_2021.csv
    - PIN1_HUMAN_Tsuboyama_2023_1I6C.csv
    - PITX2_HUMAN_Tsuboyama_2023_2L7M.csv
    - PKN1_HUMAN_Tsuboyama_2023_1URF.csv
    - PPARG_HUMAN_Majithia_2016.csv
    - PPM1D_HUMAN_Miller_2022.csv
    - PR40A_HUMAN_Tsuboyama_2023_1UZC.csv
    - PRKN_HUMAN_Clausen_2023.csv
    - PTEN_HUMAN_Matreyek_2021.csv
    - PTEN_HUMAN_Mighell_2018.csv
    - Q53Z42_HUMAN_McShan_2019_binding-TAPBPR.csv
    - Q53Z42_HUMAN_McShan_2019_expression.csv
    - RAF1_HUMAN_Zinkus-Boltz_2019.csv
    - RASH_HUMAN_Bandaru_2017.csv
    - RASK_HUMAN_Weng_2022_abundance.csv
    - RASK_HUMAN_Weng_2022_binding-DARPin_K55.csv
    - RBP1_HUMAN_Tsuboyama_2023_2KWH.csv
    - RD23A_HUMAN_Tsuboyama_2023_1IFY.csv
    - S22A1_HUMAN_Yee_2023_abundance.csv
    - S22A1_HUMAN_Yee_2023_activity.csv
    - SC6A4_HUMAN_Young_2021.csv
    - SCN5A_HUMAN_Glazer_2019.csv
    - SERC_HUMAN_Xie_2023.csv
    - SHOC2_HUMAN_Kwon_2022.csv
    - SOX30_HUMAN_Tsuboyama_2023_7JJK.csv
    - SRBS1_HUMAN_Tsuboyama_2023_2O2W.csv
    - SRC_HUMAN_Ahler_2019.csv
    - SRC_HUMAN_Chakraborty_2023_binding-DAS_25uM.csv
    - SRC_HUMAN_Nguyen_2022.csv
    - SUMO1_HUMAN_Weile_2017.csv
    - SYUA_HUMAN_Newberry_2020.csv
    - TADBP_HUMAN_Bolognesi_2019.csv
    - TNKS2_HUMAN_Tsuboyama_2023_5JRT.csv
    - TPK1_HUMAN_Weile_2017.csv
    - TPMT_HUMAN_Matreyek_2018.csv
    - TPOR_HUMAN_Bridgford_2020.csv
    - UBC9_HUMAN_Weile_2017.csv
    - UBE4B_HUMAN_Tsuboyama_2023_3L1X.csv
    - UBR5_HUMAN_Tsuboyama_2023_1I2T.csv
    - VKOR1_HUMAN_Chiasson_2020_abundance.csv
    - VKOR1_HUMAN_Chiasson_2020_activity.csv
    - YAP1_HUMAN_Araya_2012.csv
    - A0A140D2T1_ZIKV_Sourisseau_2019.csv
    - A0A192B1T2_9HIV1_Haddox_2018.csv
    - A0A1I9GEU1_NEIME_Kennouche_2019.csv
    - A0A247D711_LISMN_Stadelmann_2021.csv
    - A0A2Z5U3Z0_9INFA_Doud_2016.csv
    - A0A2Z5U3Z0_9INFA_Wu_2014.csv
    - A4D664_9INFA_Soh_2019.csv
    - A4GRB6_PSEAI_Chen_2020.csv
    - AACC1_PSEAI_Dandage_2018.csv
    - AMIE_PSEAE_Wrenbeck_2017.csv
    - ANCSZ_Hobbs_2022.csv
    - ARGR_ECOLI_Tsuboyama_2023_1AOY.csv
    - BBC1_YEAST_Tsuboyama_2023_1TG0.csv
    - BCHB_CHLTE_Tsuboyama_2023_2KRU.csv
    - BLAT_ECOLX_Deng_2012.csv
    - BLAT_ECOLX_Firnberg_2014.csv
    - BLAT_ECOLX_Jacquier_2013.csv
    - BLAT_ECOLX_Stiffler_2015.csv
    - C6KNH7_9INFA_Lee_2018.csv
    - CAPSD_AAV2S_Sinai_2021.csv
    - CAS9_STRP1_Spencer_2017_positive.csv
    - CATR_CHLRE_Tsuboyama_2023_2AMI.csv
    - CCDB_ECOLI_Adkar_2012.csv
    - CCDB_ECOLI_Tripathi_2016.csv
    - CSN4_MOUSE_Tsuboyama_2023_1UFM.csv
    - CUE1_YEAST_Tsuboyama_2023_2MYX.csv
    - D7PM05_CLYGR_Somermeyer_2022.csv
    - DLG4_RAT_McLaughlin_2012.csv
    - DN7A_SACS2_Tsuboyama_2023_1JIC.csv
    - DOCK1_MOUSE_Tsuboyama_2023_2M0Y.csv
    - DYR_ECOLI_Nguyen_2023.csv
    - DYR_ECOLI_Thompson_2019.csv
    - ENV_HV1B9_DuenasDecamp_2016.csv
    - ENV_HV1BR_Haddox_2016.csv
    - ENVZ_ECOLI_Ghose_2023.csv
    - ESTA_BACSU_Nutschel_2020.csv
    - F7YBW7_MESOW_Ding_2023.csv
    - F7YBW8_MESOW_Aakre_2015.csv
    - FECA_ECOLI_Tsuboyama_2023_2D1U.csv
    - GAL4_YEAST_Kitzman_2015.csv
    - GCN4_YEAST_Staller_2018.csv
    - GFP_AEQVI_Sarkisyan_2016.csv
    - HCP_LAMBD_Tsuboyama_2023_2L6Q.csv
    - HIS7_YEAST_Pokusaeva_2019.csv
    - HSP82_YEAST_Cote-Hammarlof_2020_growth-H2O2.csv
    - HSP82_YEAST_Flynn_2019.csv
    - HSP82_YEAST_Mishra_2016.csv
    - I6TAH8_I68A0_Doud_2015.csv
    - IF1_ECOLI_Kelsic_2016.csv
    - ISDH_STAAW_Tsuboyama_2023_2LHR.csv
    - KCNJ2_MOUSE_Coyote-Maestas_2022_function.csv
    - KCNJ2_MOUSE_Coyote-Maestas_2022_surface.csv
    - KKA2_KLEPN_Melnikov_2014.csv
    - LGK_LIPST_Klesmith_2015.csv
    - MAFG_MOUSE_Tsuboyama_2023_1K1V.csv
    - MBD11_ARATH_Tsuboyama_2023_6ACV.csv
    - MLAC_ECOLI_MacRae_2023.csv
    - MTH3_HAEAE_RockahShmuel_2015.csv
    - MYO3_YEAST_Tsuboyama_2023_2BTT.csv
    - NCAP_I34A1_Doud_2015.csv
    - NRAM_I33A0_Jiang_2016.csv
    - NUSA_ECOLI_Tsuboyama_2023_1WCL.csv
    - NUSG_MYCTU_Tsuboyama_2023_2MI6.csv
    - ODP2_GEOSE_Tsuboyama_2023_1W4G.csv
    - OXDA_RHOTO_Vanella_2023_activity.csv
    - OXDA_RHOTO_Vanella_2023_expression.csv
    - P84126_THETH_Chan_2017.csv
    - PABP_YEAST_Melamed_2013.csv
    - PA_I34A1_Wu_2015.csv
    - PHOT_CHLRE_Chen_2023.csv
    - POLG_CXB3N_Mattenberger_2021.csv
    - POLG_DEN26_Suphatrakul_2023.csv
    - POLG_HCVJF_Qi_2014.csv
    - POLG_PESV_Tsuboyama_2023_2MXD.csv
    - PSAE_SYNP2_Tsuboyama_2023_1PSE.csv
    - Q2N0S5_9HIV1_Haddox_2018.csv
    - Q59976_STRSQ_Romero_2015.csv
    - Q6WV13_9MAXI_Somermeyer_2022.csv
    - Q837P4_ENTFA_Meier_2023.csv
    - Q837P5_ENTFA_Meier_2023.csv
    - Q8WTC7_9CNID_Somermeyer_2022.csv
    - R1AB_SARS2_Flynn_2022.csv
    - RAD_ANTMA_Tsuboyama_2023_2CJJ.csv
    - RCD1_ARATH_Tsuboyama_2023_5OAO.csv
    - RCRO_LAMBD_Tsuboyama_2023_1ORC.csv
    - RDRP_I33A0_Li_2023.csv
    - REV_HV1H2_Fernandes_2016.csv
    - RFAH_ECOLI_Tsuboyama_2023_2LCL.csv
    - RL20_AQUAE_Tsuboyama_2023_1GYZ.csv
    - RL40A_YEAST_Mavor_2016.csv
    - RL40A_YEAST_Roscoe_2013.csv
    - RL40A_YEAST_Roscoe_2014.csv
    - RNC_ECOLI_Weeks_2023.csv
    - RPC1_BP434_Tsuboyama_2023_1R69.csv
    - RPC1_LAMBD_Li_2019_high-expression.csv
    - RPC1_LAMBD_Li_2019_low-expression.csv
    - RS15_GEOSE_Tsuboyama_2023_1A32.csv
    - SAV1_MOUSE_Tsuboyama_2023_2YSB.csv
    - SBI_STAAM_Tsuboyama_2023_2JVG.csv
    - SCIN_STAAR_Tsuboyama_2023_2QFF.csv
    - SDA_BACSU_Tsuboyama_2023_1PV0.csv
    - SPA_STAAU_Tsuboyama_2023_1LP1.csv
    - SPG1_STRSG_Olson_2014.csv
    - SPG1_STRSG_Wu_2016.csv
    - SPG2_STRSG_Tsuboyama_2023_5UBS.csv
    - SPIKE_SARS2_Starr_2020_binding.csv
    - SPIKE_SARS2_Starr_2020_expression.csv
    - SPTN1_CHICK_Tsuboyama_2023_1TUD.csv
    - SQSTM_MOUSE_Tsuboyama_2023_2RRU.csv
    - SR43C_ARATH_Tsuboyama_2023_2N88.csv
    - TAT_HV1BR_Fernandes_2016.csv
    - TCRG1_MOUSE_Tsuboyama_2023_1E0L.csv
    - THO1_YEAST_Tsuboyama_2023_2WQG.csv
    - TRPC_SACS2_Chan_2017.csv
    - TRPC_THEMA_Chan_2017.csv
    - UBE4B_MOUSE_Starita_2013.csv
    - VG08_BPP22_Tsuboyama_2023_2GP8.csv
    - VILI_CHICK_Tsuboyama_2023_1YU5.csv
    - VRPI_BPT7_Tsuboyama_2023_2WNM.csv
    - YAIA_ECOLI_Tsuboyama_2023_2KVT.csv
    - YNZC_BACSU_Tsuboyama_2023_2JVD.csv